### PR TITLE
Don't Apply Default Taxes to Default Free Tickets

### LINKED ISSUE #3047: Don't apply taxes to tickets by default
Taxes are applied to tickets by default, so even if you leave the price as 0.00 and publish you'll see the `*` and `* price includes taxes` on the ticket selector.

To reproduce, create a new event, set the title and datetime title and ticket title as you would.

Then view the event.

The legacy editor has taxes disabled by default so I'm guessing those shouldn't be applied here.

Also, should free tickets ever show as being taxable?

### PR DESCRIPTION
**Pull request by tn3rb**
closes #3047 

this PR checks that a default ticket is not free before applying taxes, even if those are marked as a default price

### CODE REVIEW

File: core/domain/services/admin/entities/DefaultPrices.php [hunk 1]
```diff
@@ -60,21 +60,35 @@ public function create(EE_Base_Class $entity)
...
+                ) ||(
+                    // or has fixed amount surcharge
+                    $default_price_clone->is_surcharge()
+                    && ! $default_price_clone->is_percent()
+                )) {
+                    $is_free = false;
+                }
                 $default_price_clone->set('PRC_ID', null);
                 $default_price_clone->set('PRC_is_default', false);
                 $default_price_clone->save();
```
Comment (manzoorwanijk) [inline core/domain/services/admin/entities/DefaultPrices.php:94]: This means that the base price or other non-tax default prices will still be added regardless of the ticket being free or not, right?

Comment (tn3rb) [reply core/domain/services/admin/entities/DefaultPrices.php:94]: yes correct
