### PR TITLE
Fix add new entity crash

### LINKED ISSUE #2169: Fix broken Add New Event/Datetime/Ticket
EDTR crashed when adding a new event, datetime or a ticket.

### PR DESCRIPTION
**Pull request by manzoorwanijk**
Fixes #2169 

## Checklist

* [ ] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.
* [ ] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

File: assets/prototype/domain/eventEditor/datetimes/dateForm/DateForm.js [hunk 1]
```diff
@@ -61,7 +61,7 @@ const formatSecondaryField = (ticketPrice, toString = false) => {
 
 const DateForm = ({ formReset, relatedTickets, tickets = [], title }) => {
 	const { id } = useContext(DateTimeContext);
-	const { description = '', name = '' } = useDatetimeItem({ id });
+	const { description = '', name = '' } = useDatetimeItem({ id }) || {};
```
Comment (nicolad) [inline assets/prototype/domain/eventEditor/datetimes/dateForm/DateForm.js]: :crying_cat_face:

File: assets/prototype/domain/eventEditor/tickets/ticketForm/TicketForm.js [hunk 2]
```diff
@@ -49,7 +49,7 @@ const relationsStyle = {
 
 const TicketForm = ({ datetimes, formReset, relatedDates, title }) => {
 	const { id } = useContext(TicketContext);
-	const { description = '', name = '', price = '' } = useTicketItem({ id });
+	const { description = '', name = '', price = '' } = useTicketItem({ id }) || {};
```
Comment (nicolad) [inline assets/prototype/domain/eventEditor/tickets/ticketForm/TicketForm.js]: :crying_cat_face:

File: core/domain/services/admin/events/editor/AdvancedEditorData.php [hunk 3]
```diff
@@ -180,6 +206,38 @@ protected function getEventGraphQLData($eventId)
...
+     * @throws InvalidInterfaceException
+     * @throws ModelConfigurationException
+     * @throws ReflectionException
+     * @throws UnexpectedEntityException
+     * @since $VID:$
+     */
+    protected function addDefaultEntities($eventId)
+    {
+        $default_dates = $this->datetime_model->create_new_blank_datetime();
+        if (is_array($default_dates) && isset($default_dates[0]) && $default_dates[0] instanceof EE_Datetime) {
```
Comment (nicolad) [inline core/domain/services/admin/events/editor/AdvancedEditorData.php]: can this conditional be extracted into a variable?

File: assets/prototype/domain/eventEditor/datetimes/dateForm/DateForm.js (hunk 1 above)
Comment (manzoorwanijk) [reply assets/prototype/domain/eventEditor/datetimes/dateForm/DateForm.js]: I myself am not OK with that, but it's a temporary fix and needs improvement but may be in a separate PR.

File: core/domain/services/admin/events/editor/AdvancedEditorData.php [hunk 4]
```diff
@@ -157,6 +178,11 @@ protected function getEventGraphQLData($eventId)
     {
         $datetimes = $this->getGraphQLDatetimes($eventId);
 
+        if (empty($datetimes['nodes']) || (isset($_REQUEST['action']) && $_REQUEST['action'] === 'create_new')) {
```
Comment (nicolad) [inline core/domain/services/admin/events/editor/AdvancedEditorData.php]: same as below, can we extract this in a meaningful variable, if possible?

File: assets/prototype/domain/eventEditor/datetimes/dateForm/DateForm.js (hunk 1 above)
Comment (nicolad) [reply assets/prototype/domain/eventEditor/datetimes/dateForm/DateForm.js]: Yes, I understood that it might not be smth trivial, that's why I approved the PR.

File: core/domain/services/admin/events/editor/AdvancedEditorData.php (hunk 3 above)
Comment (manzoorwanijk) [reply core/domain/services/admin/events/editor/AdvancedEditorData.php]: @tn3rb is the **owner** of that code 😄 
He knows how to handle my messed up PHP code.
