### PR TITLE
Fix Required Fields Notice Display - closes #1703

### LINKED ISSUE #1703: Remove "All fields marked with an asterisk (*) are required" text from form information
I think this message at the top of the Event Date & Ticket editors, along with the close icon next to it, isn't needed:

Screen Shot 2019-10-14 at 5 31 14 PM

Most people know that an asterisk next to a form field will mean it's required. Also in this case the required fields are automatically populated with something, and you can't blank out the required fields anyway.

### PR DESCRIPTION
**Pull request by tn3rb**
plz see #1703

this branch does the following:

- separates required fields notices from other form info notices
- moves the required fields notice to the bottom of forms
- fixes dismiss buttons so they don't display when form info isn't dismissable
- tweaks the text "focus priority" (size and colour) for form info notices and help text
- uses classNames library for setting css classes

### CODE REVIEW

File: assets/src/components/form/base/form-info-base.js [hunk 1]
```diff
@@ -38,12 +39,14 @@ const FormInfoBase = ( {
...
-		`${ classes } ee-form-info-type-${ dashicon } has-info-type` :
-		classes;
+	const classes = classNames(
+		htmlClass,
+		'ee-form-info',
+		{
+			[ `ee-form-info-type-${ dashicon }` ]: dashicon,
+			'has-info-type': dashicon,
+		}
+	);
```
Comment (manzoorwanijk) [inline assets/src/components/form/base/form-info-base.js]: 👍

File: assets/src/components/form/layouts/two-column-admin/form-section.js [hunk 2]
```diff
@@ -51,20 +52,37 @@ const FormSection = ( {
...
-	), [ showRequiredNotice ] );
-	const formErrors = hasValidationErrors ? (
-		<FormInfo
-			formInfo={ errorsNotice }
-			dashicon={ 'warning' }
-			dismissable={ false }
-		/>
-	) : null;
+	const formInfo = useMemo(
+		() => formInfoNotice ? (
```
Comment (manzoorwanijk) [inline assets/src/components/form/layouts/two-column-admin/form-section.js]: why not `formInfoNotice && ( ...` or `!! formInfoNotice && ( ...`? to be safer?

Comment (tn3rb) [reply assets/src/components/form/layouts/two-column-admin/form-section.js]: I may have done something wrong but at some point in other components I had been doing something like:

```js
const thing = showThing && <Thing />;

return (
	<SomeComponent>
		{ thing }
	</SomeComponent>
);
```

and when `showThing` was `false` I would get `0` rendered where `{ thing }` was.

Again, it's totally possible I was doing something wrong, because that was earlier on in my budding React career, but that's why I don't use that shortcut.

I did just notice that I passed the wrong dependencies to `useMemo` so I'll be pushing changes to this in a minute

Comment (manzoorwanijk) [reply assets/src/components/form/layouts/two-column-admin/form-section.js]: `false` would not render anything. Just to make sure that you are making a boolean comparison, add `!!` before the expression.

Comment (nicolad) [reply assets/src/components/form/layouts/two-column-admin/form-section.js]: Yeah, or sometimes I do this:
```
const thing = Boolean(showThing) && <Thing />;
```
If I know that `showThing` might have value `0`.
In this example `0` will be coerced to `false`.

File: assets/src/components/form/inputs/base/input-help-text.js [hunk 3]
```diff
@@ -8,7 +8,10 @@ import PropTypes from 'prop-types';
  */
 const InputHelpText = ( { helpTextID, helpText } ) => {
 	return helpText ? (
-		<p id={ helpTextID } className="espresso-input-help-text" >
+		<p
+			id={ helpTextID }
+			className={ 'espresso-input-help-text ee-focus-priority-6' }
```
Comment (nicolad) [inline assets/src/components/form/inputs/base/input-help-text.js]: `ee-focus-priority-6` - magic class name :)

https://media.giphy.com/media/12NUbkX6p4xOO4/giphy.gif

Comment (tn3rb) [reply assets/src/components/form/inputs/base/input-help-text.js]: ... not sure whether you are implying that is good ro bad { : \

here's an explanation of what all is rolled into the "focus priority" classes:
https://brent.eventespresso.com/wp-content/plugins/event-espresso-core/assets/src/components/ui/styles/themes/default/demo/index.html#font-sizes

File: assets/src/components/form/layouts/two-column-admin/form-section.js (hunk 2 above)
Comment (tn3rb) [reply assets/src/components/form/layouts/two-column-admin/form-section.js]: right I was probably getting a non-boolean falsey value...

I'll update this to use `!! formInfoNotice && `

File: assets/src/components/form/inputs/base/input-help-text.js (hunk 3 above)
Comment (nicolad) [reply assets/src/components/form/inputs/base/input-help-text.js]: Makes sense, made a search through files and stumbled across: `--ee-font-size-extreme`, `--ee-font-size-bigger` and got distracted :)

Comment (nicolad) [reply assets/src/components/form/inputs/base/input-help-text.js]: Saw this:
```
@media screen and ( max-width: 782px ) {
 .
.
.
    .ee-focus-priority-6 {
        font-size: var(--ee-font-size-smaller);
    }
.
.
.
}

```
and didn't understood at first, but after your comment got it
