### PR TITLE
Recalculate ticket prices when number of price modifiers changes - closes #1821

### LINKED ISSUE #1821: Price modifiers aren't removed when trashed
To reproduce this issue, go to the ticket price calculator modal and add a price modifier. Complete the form so the price now includes a modifier.

Then click the trash icon. The price modifier row will disappear, but you'll note that the total price includes the price modifier.

### PR DESCRIPTION
**Pull request by tn3rb**
plz see #1821

title says it all

### CODE REVIEW

File: assets/src/editor/events/tickets/editor-ticket/price-calculator/ticket-price-calculator-form-modal.js [hunk 1]
```diff
@@ -42,8 +44,12 @@ const TicketPriceCalculatorFormModal = ( {
 	const calculateTicketPrices = useCalculateTicketPrices( prices, setFormData );
 	const formDecorator = useTicketPriceCalculatorFormDecorator( setFormData );
 	useEffect( () => {
+		formData.updated = priceCount !== prevPriceCount ?
```
Comment (nicolad) [inline assets/src/editor/events/tickets/editor-ticket/price-calculator/ticket-price-calculator-form-modal.js]: Sorry for chiming in invited :)
Can this update be achieved without the need to mutate `formData`?
Or if we will create a new `formData` object, UI won't reflect the changes?

Comment (tn3rb) [reply assets/src/editor/events/tickets/editor-ticket/price-calculator/ticket-price-calculator-form-modal.js]: I'll look into that... I think I *should* be able to just spread the existing formData into a new object and then pass that along

File: assets/src/editor/events/tickets/editor-ticket/price-calculator/ticket-price-calculator-form-modal.js [hunk 2]
```diff
@@ -42,8 +44,15 @@ const TicketPriceCalculatorFormModal = ( {
 	const calculateTicketPrices = useCalculateTicketPrices( prices, setFormData );
 	const formDecorator = useTicketPriceCalculatorFormDecorator( setFormData );
 	useEffect( () => {
-		if ( pricesLoaded && formData.updated ) {
-			calculateTicketPrices( formData );
+		const data = {
```
Comment (nicolad) [inline assets/src/editor/events/tickets/editor-ticket/price-calculator/ticket-price-calculator-form-modal.js]: Thank you sir :bowing_man: 
This is awesome :+1:
