### PR TITLE
Fix no prices after creating a ticket | Closes #2632 

### LINKED ISSUE #2632: Prices disappear when creating a ticket
Steps:
- Open TPC for a ticket to make sure it has prices
- Create a new ticket
- Wait for mutation to complete
- Open TPC for the same ticket again

Prices are gone

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR fixes the issue of prices disappearing when creating a ticket which was happening because of Ticket ids not sorted when writing prices to the cache:
- Adds sorting to `ticketIn` and `datetimeIn` when writing prices and tickets cache respectively
- Updates `.map()` wherever needed to use `getGuid`.
- Closes #2632

### CODE REVIEW

File: assets/src/domain/eventEditor/services/apollo/mutations/tickets/useOnCreateTicket.ts [hunk 1]
```diff
@@ -14,7 +15,7 @@ const useOnCreateTicket = (): TicketMutationCallbackFn => {
 	const onCreateTicket = ({ proxy, datetimeIds, ticket, tickets, prices }: TicketMutationCallbackFnArgs): void => {
 		if (ticket.id) {
 			const { nodes = [] } = tickets;
-			const ticketIn = nodes.map(({ id }: Ticket) => id);
+			const ticketIn = getGuids(nodes).sort();
```
Comment (manzoorwanijk) [inline assets/src/domain/eventEditor/services/apollo/mutations/tickets/useOnCreateTicket.ts]: This is the actual fix for prices

File: assets/src/domain/eventEditor/hooks/entityListCacheUpdates/test/useUpdatePriceTypeList.test.ts [hunk 2]
```diff
@@ -59,7 +60,7 @@ describe('useUpdatePriceTypeList', () => {
 		);
 		await waitForUpdate({ timeout });
 
-		const cachedPriceTypeIds = cacheResult.current.map(({ id }) => id);
+		const cachedPriceTypeIds = getGuids(cacheResult.current);
```
Comment (tn3rb) [inline assets/src/domain/eventEditor/hooks/entityListCacheUpdates/test/useUpdatePriceTypeList.test.ts]: 👍 great, we want to reuse logic as much as possible, even for tiny things like this (also think it reads better)

File: assets/src/domain/eventEditor/services/apollo/mutations/tickets/useOnCreateTicket.ts (hunk 1 above)
Comment (tn3rb) [inline assets/src/domain/eventEditor/services/apollo/mutations/tickets/useOnCreateTicket.ts]: wow... crazy that not sorting caused an issue
