### PR TITLE
Fix TPC decimal price inputs

### LINKED ISSUE #2955: TPC Price Amount Inputs Don't Accept Decimal Values
### steps to reproduce

- open TPC for a ticket with prices (or add default prices to a free ticket)

- try to enter a price with a decimal value like `123.456`

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR fixes the decimal input issue with price inputs.
Closes #2955

### CODE REVIEW

File: assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/fields/BaseNumberInputField.tsx [hunk 1]
```diff
@@ -31,7 +31,10 @@ const BaseNumberInputField: React.FC<BaseFieldProps> = ({
 			showStepper={false}
 			onChange={onChange}
 			placeholder={placeholder}
-			value={fieldValue}
+			// lets leave the input uncontrolled and just pass the default value
+			// just to be avoid storing local state for formatting the decimal value
+			// and sync the value directly with TPC state
+			defaultValue={fieldValue}
```
Comment (nicolad) [inline assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/fields/BaseNumberInputField.tsx:37]: hmm, interesting
