### PR TITLE
Fix TPC ticket update | Closes #2493

### LINKED ISSUE #2493: "Error Updating Ticket" After Editing Price
- click on ticket price calculator icon for a ticket

- edit the price and click submit

- watch the toaster notifications in the bottom right of the screen, you will see the following:

    - updating price

    - successfully updated price

    - updating ticket

    - error updating ticket

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR
- Removes `isFree` field from ticket mutation input
- Tightens the type checks for TPC fields.
- Closes #2493

### CODE REVIEW

File: assets/src/domain/shared/entities/prices/predicates/priceFields.ts [hunk 1]
```diff
@@ -1,4 +1,6 @@
-export const PRICE_INPUT_FIELDS = [
+import { UpdatePriceInput } from '@edtrServices/apollo/mutations';
+
+export const PRICE_INPUT_FIELDS: Array<keyof UpdatePriceInput> = [
```
Comment (nicolad) [inline assets/src/domain/shared/entities/prices/predicates/priceFields.ts]: nice :+1:
