### PR TITLE
Fix quantity cap for new ticket

### LINKED ISSUE #2962: New Ticket Quantity Not Capped at Datetime Capacity
### steps to reproduce

- create or edit a date and give it a finite capacity like 100

- create a new ticket but do not set a quantity for available tickets, making it an infinite quantity

- assign the ticket to the date with the finite capacity

- after creation, the new ticket will show infinity for its quantity

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR fixes the issue of quantity cap for new tickets

Closes #2962

### CODE REVIEW

File: assets/src/domain/eventEditor/ui/tickets/hooks/useCapQuantity.ts [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+ * based on the related dates capacity
+ */
+const useCapQuantity = (ticketId?: EntityId): Callback => {
+	const allDates = useDatetimes();
+	const allTickets = useTickets();
+	const { getData: getExistingData } = useRelations();
+
+	return useCallback<Callback>(
+		(relatedDateIds, quantity) => {
+			if (!relatedDateIds?.length) {
```
Comment (nicolad) [inline assets/src/domain/eventEditor/ui/tickets/hooks/useCapQuantity.ts:21]: :+1:
