### PR TITLE
Fix price deletion

### LINKED ISSUE #2900: Prices not deleted permanently
While working on #2899, I noticed that when prices are deleted permanently, there is some server-side error.

**Steps:**
1. Trash a Ticket that has at least one non-default price
2. In filter bar, set to view trashed tickets
3. Delete the above trashed ticket permanently

**Expected**: Ticket and the related non-default price should permanently be deleted.

**Actual**: There is a server-side error that says: `The price could not be deleted because of the following error(s): A valid price could not be retrieved from the database.`

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR updates ticket deletion to delete related prices from Apollo cache when ticket is permanently.

Closes #2900

### CODE REVIEW

File: assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts [hunk 1]
```diff
@@ -1,36 +1,58 @@
...
-		priceIdsToDelete.forEach((id) => {
-			deletePrice({ id, deletePermanently: true });
+		// read existing data from Apollo cache
+		const data = client.readQuery<PricesList>(priceQueryOptions);
+		// filter out the related prices from Apollo cache data
+		const pricesToRetain = data?.espressoPrices?.nodes?.filter(({ id }) => !priceIdsToDelete.includes(id)) || [];
+		// avoid the dirty object creation using assocPath
+		const newData = assocPath(['espressoPrices', 'nodes'], pricesToRetain, data);
+
+		// write the data back to cache
```
Comment (nicolad) [inline assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts:39]: came here for the comments :+1:

File: assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts [hunk 2]
```diff
@@ -1,36 +1,58 @@
 import { useCallback } from 'react';
 
 import useTicketPrices from '@edtrServices/apollo/queries/tickets/useTicketPrices';
-import { EntityId } from '@dataServices/types';
-import { useTicketMutator, usePriceMutator } from '@edtrServices/apollo/mutations';
+import type { EntityId } from '@dataServices/types';
```
Comment (tn3rb) [inline assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts:5]: oooooo new TS Voodoo...  what does this do?

File: assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts [hunk 3]
```diff
@@ -1,36 +1,58 @@
...
+		if (!pricesToDelete.length) {
+			return;
+		}
 		const priceIdsToDelete = getGuids(pricesToDelete);
-		priceIdsToDelete.forEach((id) => {
-			deletePrice({ id, deletePermanently: true });
+		// read existing data from Apollo cache
+		const data = client.readQuery<PricesList>(priceQueryOptions);
+		// filter out the related prices from Apollo cache data
+		const pricesToRetain = data?.espressoPrices?.nodes?.filter(({ id }) => !priceIdsToDelete.includes(id)) || [];
```
Comment (nicolad) [inline assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts:35]: not sure about that `id` destructuring, in case when node is undefined;
what do you think of:
```
		const pricesToRetain = data?.espressoPrices?.nodes?.filter(node => !priceIdsToDelete.includes(node?id)) || [];
```

Comment (manzoorwanijk) [reply assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts:35]: If `nodes` is `undefined`, the filter won't be called :)

Comment (manzoorwanijk) [reply assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts:35]: image

Comment (nicolad) [reply assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts:35]: just checked, as you wrote is safe enuf:

image

Comment (tn3rb) [reply assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts:35]: mmmm... dunno if that's any clearer... 
considering it's passing the `id` to `priceIdsToDelete` i think it can easily be inferred that those are price IDs
imho

Comment (manzoorwanijk) [reply assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts:35]: Yes, optional chaining "breaks the chain" whenever it finds `null` or `undefined`

File: assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts (hunk 2 above)
Comment (manzoorwanijk) [reply assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts:5]: No, not new, you forgot your [own comment](https://github.com/eventespresso/event-espresso-core/pull/2608#discussion_r401781465) 😄

File: assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts (hunk 3 above)
Comment (nicolad) [reply assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts:35]: I think more extracting might be clearer:
```
const prices = data?.espressoPrices?.nodes;
const pricesToRetain = prices?.filter(({ id }) => !priceIdsToDelete.includes(id)) ?? [];
```

File: assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts (hunk 2 above)
Comment (tn3rb) [reply assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts:5]: well of course I did, that was months ago
