### PR TITLE
Fix TAM entity details in multi step

### LINKED ISSUE #2954: New Entity Details Missing in TAM Form Step
### steps to reproduce 

- click the "Add New Date" or "Add New Ticket" button

- enter entity details in form step one, then click to advance to the ticket assignments form step

- new entity details entered in step 1 such as name, start date, and price, do not appear in entity details in TAM

add new date edit form TAM step

ScreenShot_20200611123539

add new ticket edit form TAM step

ScreenShot_20200611122051

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR fixes the issue of entity details in multi-step form not being synced with TAM step with the following changes:
- Creates `useMemoLazy` 😎 
- Creates `withEntityFormDetails` HOC to share between date and ticket multi-step form
- Updates date and ticket muti-step to use the entity details from edit form
- Fixes and improves TAM to use the supplied entity details

Closes #2954

### CODE REVIEW

File: assets/src/application/services/hooks/useMemoLazy.ts [hunk 1]
```diff
@@ -0,0 +1,30 @@
+import { useRef, useCallback } from 'react';
+
+/**
+ * This custom hook can be used to memoize a value lazily
+ * i.e. its returned callback can be used at the places where a hook cannot be used
```
Comment (nicolad) [inline assets/src/application/services/hooks/useMemoLazy.ts:5]: yasss

File: assets/src/domain/shared/ui/entityEditModal/withEntityFormDetails.tsx [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+    // We only need value here.
+	const subscription = useMemoStringify({ values: true });
+	return (
+		<FormSpy subscription={subscription}>
+			{({ values: { dateTime, ...values } }) => {
+				const entity = lazyMemo({
+					...values,
+                    id: values.id ?? newEntityId,
+                    dbId: values.dbId ?? 0,
+					...processDateAndTime(dateTime, siteTimeToUtc),
```
Comment (nicolad) [inline assets/src/domain/shared/ui/entityEditModal/withEntityFormDetails.tsx:28]: interesting approach
