### PR TITLE
Fix WP GraphQL v0.6.0 fatal error | Closes #2562

### LINKED ISSUE #2562: Fatal Errors with WP GraphQL v0.7.0
Josh attempted to check out the EDTR master branch but immediately ran into issues because he also happened to be on version `0.7.0` of WP GraphQL, which is incompatible with our implementation:

```php
Fatal error:  Class EventEspresso\core\domain\services\graphql\connection_resolvers\DatetimeConnectionResolver
contains 1 abstract method and must therefore be declared abstract
or implement the remaining methods
(WPGraphQL\Data\Connection\AbstractConnectionResolver::is_valid_offset)
in
/core/domain/services/graphql/connection_resolvers/DatetimeConnectionResolver.php on line 19
```

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR fixes the fatal error caused after WP GraphQL v0.6.0, due to a new abstract method `is_valid_offset` in `WPGraphQL\Data\Connection\AbstractConnectionResolver`.

**Changes:**
- Added `is_valid_offset` method to `AbstractConnectionResolver` to cater for all the connection resolvers that extend it.

Closes #2562

### CODE REVIEW

File: assets/src/application/ui/input/InlineEditInput/Editable.tsx [hunk 1]
```diff
@@ -13,14 +13,21 @@ const EditableTypes = {
...
 
 	const htmlClasses = classNames('ee-inline-edit', `ee-inline-edit-${inputType}`, className);
 
-	return <Component className={htmlClasses} editable={{ onChange }} ellipsis={ellipsis} tabIndex={0} {...rest} />;
+	return (
+		<Component
+			className={htmlClasses}
+			editable={{ onChange }}
+			// TS treats ellipsis as a prop for Typography.Text
+			ellipsis={ellipsis as boolean}
```
Comment (nicolad) [inline assets/src/application/ui/input/InlineEditInput/Editable.tsx]: this is named type casting, as you wrote yesterday, right?

Comment (manzoorwanijk) [reply assets/src/application/ui/input/InlineEditInput/Editable.tsx]: Yes

File: core/domain/services/graphql/connection_resolvers/AbstractConnectionResolver.php [hunk 2]
```diff
@@ -34,6 +35,25 @@ protected function getLimit()
         return $limit;
     }
 
+    /**
+     * Determine whether or not the the offset is valid, i.e the entity corresponding to the
+     * offset exists. Offset is equivalent to entity ID. So this function is equivalent to
```
Comment (nicolad) [inline core/domain/services/graphql/connection_resolvers/AbstractConnectionResolver.php]: didn't knew that `Offset is equivalent to entity ID`

Comment (manzoorwanijk) [reply core/domain/services/graphql/connection_resolvers/AbstractConnectionResolver.php]: In cursor based pagination (use by GraphQL/Relay), offset is always an entity ID which makes things faster.

File: core/domain/services/graphql/connection_resolvers/AbstractConnectionResolver.php [hunk 3]
```diff
@@ -34,6 +35,25 @@ protected function getLimit()
...
+     * @access public
+     *
+     * @param int $offset The ID of the node used for the cursor offset
+     *
+     * @return bool
+     */
+    // phpcs:ignore PSR1.Methods.CamelCapsMethodName.NotCamelCaps
+    public function is_valid_offset($offset)
+    {
+        $entity = $this->get_query()->get_one_by_ID($offset);
```
Comment (nicolad) [inline core/domain/services/graphql/connection_resolvers/AbstractConnectionResolver.php]: googled this and got results to our docs :)

image
