### PR TITLE
IsChainedButton fix and ant styles removal; closes #2678 and #2725.

### LINKED ISSUE #2678: Post AntD Cleanup
Cleanup package.json and any other build/configuration files to remove all traces of AntD and other purged dependencies

### PR DESCRIPTION
**Pull request by nicolad**
## Problem this Pull Request solves
- Fixes `IsChainedButton` height and hover.
- Closes: https://github.com/eventespresso/event-espresso-core/issues/2678 and https://github.com/eventespresso/event-espresso-core/issues/2725

### CODE REVIEW

File: assets/src/domain/shared/entities/datetimes/predicates/isRecentlyExpired/index.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@ import { parseISO } from 'date-fns';
 import { Datetime } from '@edtrServices/apollo/types';
 import { diff } from '@appServices/utilities';
 import { now } from '@sharedServices/utils/dateAndTime';
-import TIME from '../../../../../../application/constants/time';
+import TIME from '@appConstants/time';
```
Comment (manzoorwanijk) [inline assets/src/domain/shared/entities/datetimes/predicates/isRecentlyExpired/index.ts:6]: 👍
