### PR TITLE
Fix Hidden Ticket Selector Details Row 

### LINKED ISSUE #3244: Ticket Selector Ticket Rows Hidden if Event Has Only 1 Ticket
see: https://github.com/eventespresso/event-espresso-core/issues/3228

### steps to reproduce

- find event with only one ticket (or create one)

- visit event listing on frontend

- ticket is hidden because of code added in 3228

### PR DESCRIPTION
**Pull request by tn3rb**
This PR fixes an issue introduced by #3228

closes #3244

### CODE REVIEW

**Comment by garthkoyle** [comment]
@tn3rb can this be closed?

**Comment by tn3rb** [comment]
LOLZ

no

I just created this like 5 minutes ago

File: modules/ticket_selector/assets/ticket_selector.js [hunk 1]
```diff
@@ -128,4 +128,40 @@ jQuery(document).ready(function ($) {
 		$( this ).click();
 	} );
 
+
+	$('.display-tckt-slctr-tkt-details').on(
+		'click',
+		function () {
+			// get target element from "this" (the control element's) "rel" attribute
+			var target = $(this).attr("rel");
+			if (target.length) {
```
Comment (nicolad) [inline modules/ticket_selector/assets/ticket_selector.js:137]:
```suggestion
			if (target?.length) {
```
maybe?

Comment (tn3rb) [reply modules/ticket_selector/assets/ticket_selector.js:137]: don't think that will work because this code doesn't run through babel/webpack or whatever does all of that magic of converting ES6 to vanilla JS

Comment (manzoorwanijk) [reply modules/ticket_selector/assets/ticket_selector.js:137]: `target.length` is always defined in that case and defaults to `0`

**Review by manzoorwanijk — APPROVED** [review]
Looks great 🚀

File: modules/ticket_selector/assets/ticket_selector.js (hunk 1 above)
Comment (tn3rb) [reply modules/ticket_selector/assets/ticket_selector.js:137]: right.. jQuery always returns an object and checking its length is the easiest way to confirm that it is the expected DOM element
