### PR TITLE
Fix TPC tax deletion issue

### LINKED ISSUE #2934: TPC Issues: Price Order Not Set Correctly && Taxes Applied After Deleting Prices
### Steps to Reproduce

- use https://brent.eventespresso.com/

- create a new ticket and on the TPC form step click Add Default Prices

- set base ticket price to $10 and leave tax as is

- save, assign a date, save new ticket, and wait for mutations to complete

- click TPC icon to edit prices

- delete all prices and submit

- click TPC icon again to edit prices

- **???** default tax appears again despite having been deleted

- if you monkey around with variations of the above steps you can sometimes get the default base price to appear AFTER the default tax, but this can not be reproduced reliably and seems to happen almost randomly, but essentially, the PRC_order is not getting set. I've looked directly in the db on my testing site and most of the prices have an order of 0. You can use this tool by going to https://brent.eventespresso.com/wp-admin/tools.php?page=databasebrowser

So looks like two things need to happen

- `isTaxable` needs to be set back to `false` when ALL prices are deleted

- `PRC_order` field needs to get set upon save. This will be a bit tricky because the order of the default taxes can not be modified, so all prices and modifiers prior to taxes can simply be ordered sequentially (1,2,3...) but any that appear after taxes will need to start from the highest order of the last tax (ie, if the last tax has an order of 70, then the next modifier needs to start at 71, although it might be wise to put a bigger gap between taxes and any additional prices (like start at 80)

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR fixes the issue of default tax not being removed from a ticket with the following changes:
- Allows empty `prices` array in GQL schema to be handled in ticket update mutation
- Creates tax removal hooks - `useRemoveAllTaxes` (for #2949) and `useRemoveDefaultTax`
- Wires up price deletion buttons
Closes #2934

### CODE REVIEW

File: assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/DeleteAllPricesButton.tsx [hunk 1]
```diff
@@ -5,24 +5,31 @@ import { ConfirmDelete } from '@appDisplay/confirm';
...
 		buttonType: ButtonType.ACCENT,
 	});
 	const onConfirm = useCallback(() => {
-		prices.forEach(({ id, isNew, isDefault }) => {
-			deletePrice(id, isNew || isDefault);
+		prices.forEach((price) => {
+			// delete the price from TPC state
+			deletePrice(price.id, price.isNew || price.isDefault);
+			// Remove default tax from relations
+			removeDefaultTax(price);
```
Comment (nicolad) [inline assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/DeleteAllPricesButton.tsx:23]: nice

File: assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useRemoveAllTaxes.ts [hunk 2]
```diff
@@ -0,0 +1,22 @@
+import { useCallback } from 'react';
+
+import { useDataState } from '../data';
+import useRemoveDefaultTax from './useRemoveDefaultTax';
+import { isTax } from '@sharedEntities/priceTypes/predicates';
+
+const useRemoveAllTaxes = (): VoidFunction => {
```
Comment (nicolad) [inline assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useRemoveAllTaxes.ts:7]: this is cool :sunglasses:
