### PR TITLE
Fix date formats and validations | Closes #2753

### LINKED ISSUE #2753: On datetime update start date is wrongly changed
When updating datetime name and description start date is wrongly changed:

Peek 2020-04-30 16-20

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR:
- Fixes the issue of random date change for dates and tickets due to format mismatch
- Fixes the validation and error message for dates and times

### CODE REVIEW

File: assets/src/application/services/utilities/date/misc.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import { setHours, setMinutes, setSeconds, setYear, setMonth, setDate } from 'date-fns';
+
+/**
+ * Sets the time of the date object to zero hour
+ */
+export const setTimeToZeroHour = (date: Date): Date => setSeconds(setMinutes(setHours(date, 0), 0), 0);
```
Comment (nicolad) [inline assets/src/application/services/utilities/date/misc.ts:6]: I see `pipe` here :) 

based on:

image

File: assets/src/application/services/utilities/date/misc.ts [hunk 2]
```diff
@@ -12,5 +12,10 @@ export const setTimeToZeroHour = (date: Date): Date => pipe(setHours(0), setMinu
 export const setDateToToday = (date: Date): Date => {
 	const today = new Date();
 
-	return pipe(setDate(today.getDate()), setMonth(today.getMonth()), setYear(today.getFullYear()))(date);
+	// prettier-ignore
```
Comment (nicolad) [inline assets/src/application/services/utilities/date/misc.ts:15]: instead of ignore another solution:

image

File: assets/src/application/services/utilities/date/misc.ts [hunk 3]
```diff
@@ -1,14 +1,16 @@
...
+export const setTimeToZeroHour = (date: Date): Date => pipe(setHours(0), setMinutes(0), setSeconds(0))(date);
 
 /**
  * Sets the date, month and year of the date object to those of today
  */
 export const setDateToToday = (date: Date): Date => {
 	const today = new Date();
-	return setYear(setMonth(setDate(date, today.getDate()), today.getMonth()), today.getFullYear());
+
+	return pipe(setDate(today.getDate()), setMonth(today.getMonth()), setYear(today.getFullYear()))(date);
```
Comment (manzoorwanijk) [inline assets/src/application/services/utilities/date/misc.ts]: Thanks @nicolad
