### PR TITLE
Fix base price when ticket price is changed inline

### LINKED ISSUE #3016: Editing a 'free' ticket price from the card, does not save the price on the ticket
Add a ticket, skip pricing and select a datetime.

You'll end up with a ticket like this:
https://monosnap.com/file/0Ijre7py6TrEbkE5ezfXm0sCfDGRB1

Now edit the price from the card:
https://monosnap.com/file/tK8np6jmy07Xk6kaIRrvk3XbuR6A0w

The front end shows a free ticket:
https://monosnap.com/file/yWxOGfKhjFRezqbjxCm9Sb98nbNGH3

Open the TPC and it shows no pricing, ticket is free:
https://monosnap.com/file/FaCpovpcqssUieCkV8YJplweQI53eI

Click to add default pricing and it 'correctly' calculates the price from the bottom up:
https://monosnap.com/file/0luYFJtQdCuPSqUn6ZbPmjxfIQNGwl

Ticket price on the front end how shows pretax:
https://monosnap.com/file/Su7rdiyGOCTkoAXgqaZkdbpikYg5ss

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR fixes the base price creation/update when the ticket price is updated inline.

Closes #3016 #3017

### CODE REVIEW

File: assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useAddDefaultPrices.ts [hunk 1]
```diff
@@ -1,24 +1,19 @@
...
 
 const useAddDefaultPrices = (): VoidFunction => {
-	const allPriceTypes = usePriceTypes();
 	const allPrices = usePrices();
 	const defaultPrices = allPrices.filter(isDefault);
-	const [basePriceType] = allPriceTypes.filter(isBasePrice);
 
-	const defaultPriceModifier = usePriceModifier(defaultPrice);
-	const basePrice = updatePriceModifier(defaultPriceModifier, basePriceType);
+	const basePrice = useDefaultBasePrice();
```
Comment (manzoorwanijk) [inline assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useAddDefaultPrices.ts:16]: Extracted this to a hook for reusability

File: assets/src/domain/eventEditor/ui/tickets/hooks/useRecalculateBasePrice.ts [hunk 2]
```diff
@@ -3,27 +3,53 @@ import { useCallback } from 'react';
...
+			const exitingBasePrice = getBasePrice(tpcData?.prices);
+			// if the ticket does not have a base price,
+			// that means it was free and now a price has been added ¯\_(ツ)_/¯
+			if (!exitingBasePrice) {
+				const newPrices = [
+					// add the default price
+					{ ...defaultBasePrice, order: 1, isNew: true },
+					// add the existing ones, just in case we are dealing with aliens,
+					// don't get me wrong, because only they can have other prices without a base price,
+					// may be their taxation systen works differently, who knows ¯\_(ツ)_/¯
```
Comment (nicolad) [inline assets/src/domain/eventEditor/ui/tickets/hooks/useRecalculateBasePrice.ts:32]: this is hilarious
