### PR TITLE
Fix the z-index for EDTR modals; closes #2022.

### LINKED ISSUE #2022: Fix the z-index for EDTR modals
When a modal is open, the default WP content editor blocks some of the modal.

image

### PR DESCRIPTION
**Pull request by nicolad**
## Problem this Pull Request solves
Fixes: https://github.com/eventespresso/event-espresso-core/issues/2022

The reason that happened was because the WP content editor tools' `z-index` was `1000`:
image

But `blueprintjs`'s modal has it's `z-index` set to `20` (why not :smiley:  )
image

I've overriden `20` with `1400`:

image

It's the value I've seen in `chakra-ui`: https://github.com/chakra-ui/chakra-ui/blob/master/packages/chakra-ui-docs/pages/theme.mdx#z-index

## Checklist

* [ ] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.
* [ ] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

File: assets/prototype/domain/eventEditor/data/queries/useCacheRehydration.js [hunk 1]
```diff
@@ -24,62 +25,72 @@ const useCacheRehydration = () => {
...
-	let { nodes = [] } = espressoPriceTypes;
-	if (nodes.length) {
-		client.writeQuery({
-			query: GET_PRICE_TYPES,
-			data: {
-				espressoPriceTypes,
-			},
-		});
-	}
+	Object.entries({ priceTypes: espressoPriceTypes, datetimes: espressoDatetimes, tickets: espressoTickets }).forEach(
```
Comment (nicolad) [inline assets/prototype/domain/eventEditor/data/queries/useCacheRehydration.js]: Let me know if this isn't making grokking worse.
