### PR TITLE
Fix priority for filters and sorters | Closes #2736

### LINKED ISSUE #2736: Priority for entity list filters and sorters doesn't seem to be wired up
It looks like  we missed the priority arg for filters and sorters due to which it's possible that the result may not be as desired. For example, we need to make sure that sales filter for dates should run after status filter even if later is registered first.

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR adds support for priority argument for filters and sorters.

### CODE REVIEW

File: assets/src/application/ui/layout/entityList/filterBar/filterState/useEntityFilterService.ts [hunk 1]
```diff
@@ -17,7 +18,8 @@ const useEntityFilterService = <D extends string, L extends string, E extends En
 	const getCallbackList = (
 		mappedCallbackList: ReturnType<typeof getFilters>
 	): Array<SubscriptionCallback<FilterBarServiceCbArgs<E, ELFSM>, E[]>> => {
-		return Object.values(mappedCallbackList).map(({ callback }) => callback);
+		const subscriptions = sortBy(pathOr(10, ['options', 'priority']), Object.values(mappedCallbackList));
```
Comment (nicolad) [inline assets/src/application/ui/layout/entityList/filterBar/filterState/useEntityFilterService.ts:21]: nice extraction :+1:

File: assets/src/domain/eventEditor/services/filterState/tickets/useTicketsFilterBarService.ts [hunk 2]
```diff
@@ -39,7 +39,7 @@ const useTicketsFilterBarService = (): void => {
 		// Register isChained filter
 		const unSubscribeIsChainedFilter = registerTicketsFilter(({ entityList, filterState }) => {
 			return isChainedFilter({ isChained: filterState.isChained, tickets: entityList });
-		});
+		}, 9); // we want isChained to run first
```
Comment (nicolad) [inline assets/src/domain/eventEditor/services/filterState/tickets/useTicketsFilterBarService.ts:42]: :+1:
