### PR TITLE
Fix Drag-n-Drop when not sorting | Closes #2743

### LINKED ISSUE #2743: Table View Rows Can Be "Dragged n Dropped" Even If Sorting Has Not Been Enabled
Title says it all:

- click on the Table View button in the Entity List filter bar

- "grab" a row

- "drag" a row

- "drop" a row (doesn't actually result in order being changed)

- works even when there is only ONE row in the Entity List

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR disables drag and drop when sorting is not enabled.

### CODE REVIEW

File: assets/src/application/ui/layout/entityList/EntityTable.tsx [hunk 1]
```diff
@@ -28,14 +28,15 @@ const EntityTable = <E extends Entity, FS extends ELFSM>({
 		tableId,
 		tableCaption,
 	};
+	const onDragEnd = filterState.sortingEnabled ? onSort : null;
```
Comment (nicolad) [inline assets/src/application/ui/layout/entityList/EntityTable.tsx:31]: makes sense :+1:
