### PR TITLE
Fix Ticket Selector Caps Restrictions Issue

### LINKED ISSUE #3670: Fix wrong ticket selected when some tickets aren't available due to caps
Reported here: https://eventespresso.com/topic/ticket-type-changes-on-checkout/

I think this is a new issue with the ticket selector row count.

You need at least the first ticket on the event to be limited by a capability you don't have to reproduce this so first, steps to setup the event.

(You need the WP User integration add-on enabled for this)

Create a new event.

On the single default ticket, set the name to be 'Ticket 1' so you can follow along.

Duplicate that ticket 4 times (so a total of 5 tickets)

Rename the tickets in order 1-5 (so you have Ticket 1, Ticket 2, Ticket 3...) this is just so this next part makes sense when explaining.

Edit Ticket 1 and set the required capability to 'something'

Edit Ticket 2 and set the required capability to 'something'

(I literally mean 'something' here, a cap that you will never have on your account)

Set 'Maximum number of tickets allowed per order for this event:' to 1.

Publish the event and try to register onto Ticket 3.

The checkout page shows 'Ticket 1' was added to the cart.

Ticket selector: https://monosnap.com/file/Kv64sEjj3EPBT8PQe8HDRRKpqvbGX6
Testing ticket types – EE4 Beaver Bulder - Google

Checkout: https://monosnap.com/file/mDwlkPn1fsJzo009QuDg6DMXIG94dI
Registration Checkout – EE4 Beaver Bulder - Google

(Ticket 4, shows Ticket 2..... you guessed it, Ticket 5 shows Ticket 3)

Looks like the count is off by however many 'unavailable' tickets are at the beginning.

### PR DESCRIPTION
**Pull request by tn3rb**
This PR:

- closes #3670
- adds a unit test to demonstrate the bug and confirm the subsequent fix
- changes how the ticket selector ticket quantity inputs are named by using the ticket ID for the keys (i'm not entirely sure why this wasn't done earlier but I'm guessing there was something about the original TS that prevented it)
- changes the POST processing to directly obtain selected ticket quantities using the ticket IDs instead of the row key

### CODE REVIEW

**Review by knazart — APPROVED** [review]
Looks good to me.

**Comment by Pebblo** [comment]
Howdy Brent, something weird going on here.

(Note the event setup in the issue for testing this)

Ticket 3 now works great.

Ticket 4 and 5 are both showing the "You need to select a ticket qty..." error:

https://monosnap.com/file/D3Y87GWvSHlnLwsUIOYfgujj9dHHW3

Also noticed that in this branch I can now select multiple radio buttons fields:

https://monosnap.com/file/GbIYowd4nxD7SlqisY8XvbYJ0ZuW3z

**Comment by tn3rb** [comment]
> Ticket 4 and 5 are both showing the "You need to select a ticket qty..." error:

ahh I'm sorry... i failed to check that the other ticket options still worked correctly

> Also noticed that in this branch I can now select multiple radio buttons fields:

### **DOH!!!** 😖 

well that explains this comment i made:
> i'm not entirely sure why this wasn't done earlier but I'm guessing there was something about the original TS that prevented it

uh ya.. it was the radio buttons that prevent that option from working

File: modules/ticket_selector/ProcessTicketSelectorPostData.php [hunk 1]
```diff
@@ -192,12 +175,19 @@ protected function processQuantity($input_key)
...
+        // ex: row qty = [ 0 => TKT_ID ]
+        if ($max_atndz === 1 && count($row_qty) === 1) {
+            // so we'll grab that ticket ID, use it as the key, and set the value to 1
+            // ex: row qty = [ TKT_ID => 1 ]
+            $ticket_id = array_pop($row_qty);
+            $row_qty = [ $ticket_id => 1 ];
+        }
+        foreach ($this->valid_data[ self::DATA_KEY_TICKET_ID ] as $ticket_id) {
+            $qty = isset($row_qty[ $ticket_id ]) ? $row_qty[ $ticket_id ] : 0;
+            $this->valid_data[ self::DATA_KEY_QUANTITY ][ $ticket_id ]     = $qty;
```
Comment (tn3rb) [inline modules/ticket_selector/ProcessTicketSelectorPostData.php:190]: this means that regardless of the TS format (dropdown, radio buttons, DWMTS) the final valid data array will have the ticket selections in the format: `[ TKT ID => QTY ]`

Comment (Pebblo) [reply modules/ticket_selector/ProcessTicketSelectorPostData.php:190]: Liking this! Much easier to follow 👍

**Review by Pebblo — APPROVED** [review]
Code looks good to me, please see my reply in the PR

**Comment by tn3rb** [comment]
I'm so sorry Tony, I totally forgot to test MER 🤦🏻 
glad you're testing skilly are so excellent 🙇🏻

**Comment by Pebblo** [comment]
This looks like it's resolved :)

Thanks @tn3rb.
