### PR TITLE
Ensure Template Helper is Loaded for Espresso Shortcodes

### LINKED ISSUE #3643: Change in behaviour - espresso_get_template_part not available?
Looks like template_tags.php is no longer available when processing custom shortcodes.

This: [ee-past-events-shortcode.zip](https://github.com/eventespresso/event-espresso-core/files/7653037/ee-past-events-shortcode.zip) 

Is a plugin Josh created for a user a while back to display only previous events, it's been working up until version 4.10.14.p where it now throws:

```
[04-Dec-2021 00:50:18 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function espresso_get_template_part() in C:\laragon\www\ee4\wp-content\plugins\ee-past-events-shortcode\shortcode-template.php:8
Stack trace:
#0 C:\laragon\www\ee4\wp-content\plugins\ee-past-events-shortcode\ee_shortcode_past_events.php(50): include_once()
#1 C:\laragon\www\ee4\wp-includes\shortcodes.php(356): my_ee_past_events_shortcode(Array, '', 'espresso_past_e...')
#2 [internal function]: do_shortcode_tag(Array)
#3 C:\laragon\www\ee4\wp-includes\shortcodes.php(228): preg_replace_callback('/\\[(\\[?)(espres...', 'do_shortcode_ta...', '[espresso_past_...')
#4 C:\laragon\www\ee4\wp-includes\class-wp-hook.php(303): do_shortcode('[espresso_past_...')
#5 C:\laragon\www\ee4\wp-includes\plugin.php(189): WP_Hook->apply_filters('[espresso_past_...', Array)
#6 C:\laragon\www\ee4\wp-includes\post-template.php(253): apply_filters('the_content', '[espresso_past_...')
#7 C:\laragon\www\ee4\wp-content\themes\twentyfifteen\content-page.php(22): the_content()
#8 C:\laragon\www\ee4\wp-incl in C:\laragon\www\ee4\wp-content\plugins\ee-past-events-shortcode\shortcode-template.php on line 8
```

Are those `EEH_Template.helper` functions no longer loading?

**To Reproduce**
Use the above custom plugin and just add `[espresso_past_events]` to a page, then view the front end.

Gutenburg editor also throws a fatal with this.

### PR DESCRIPTION
**Pull request by tn3rb**
This PR:

- closes #3643 
- improves logic pertaining to retrieval of post content by first checking for global post object
- adds wildcard check for any shortcode starting with `[espresso_`
- ensures that `CurrentPage::testForEspressoPage()` is called when checking `isEspressoPage()`
- manually loads `EEH_Template` if `isEspressoPage()` is `true`

### CODE REVIEW

File: core/services/request/CurrentPage.php [hunk 1]
```diff
@@ -187,7 +187,7 @@ private function getPostName(WP $WP = null)
             }
             // this stinks but let's run a query to try and get the post name from the URL
             // (assuming pretty permalinks are on)
-            if (! $post_name && $WP->request !== null && ! empty($WP->request)) {
```
Comment (tn3rb) [inline core/services/request/CurrentPage.php:190]: removed because redundant and checked via `empty()` call

File: core/services/request/CurrentPage.php [hunk 2]
```diff
@@ -247,6 +247,9 @@ private function getPostType(WP $WP = null)
      */
     public function isEspressoPage()
     {
+        if ($this->is_espresso_page === null) {
+            $this->setEspressoPage();
+        }
```
Comment (tn3rb) [inline core/services/request/CurrentPage.php:252]: changed default value for property from `false` and then use `null` value to trigger check

**Review by knazart — APPROVED** [review]
Look good.

**Comment by Pebblo** [comment]
Thanks, Brent.

Tested and confirmed.
