### PR TITLE
Fix price_type hydration

### LINKED ISSUE #1780: JS error: TypeError: priceTypeEntity is undefined when updating a price via the Card UI
Store rehydration does not update the `price_type` list in `'eventespresso/lists'`, which means no price types are available.

### PR DESCRIPTION
**Pull request by manzoorwanijk**
## Problem this Pull Request solves
Fixes #1780 #1778 

## How has this been tested
monkey and unit tests

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [x] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

File: assets/src/editor/events/initialization/data-hydrator.js [hunk 1]
```diff
@@ -136,7 +137,14 @@ const hydrateEntityData = async ( rawData, schemas ) => {
...
 				}
 			);
-			resolveGetEntities( model );
+			if ( model === 'price_type' ) {
+				receiveEntityResponse(
+					model,
+					undefined,
+					Object.values( entities[ model ] ),
+				);
+				resolveGetEntities( model );
```
Comment (tn3rb) [inline assets/src/editor/events/initialization/data-hydrator.js]: this was previously being done for all entities but now it is only happening for prices?!?!?!
was this supposed to be after the closing brace that follows it? 
ie: we just need to receive price types prior to calling `resolveGetEntities( model )` ?

Comment (manzoorwanijk) [reply assets/src/editor/events/initialization/data-hydrator.js]: We just need that for `price_type`, doing for others doesn't really matter, that's why I moved it inside that block.
