### PR TITLE
Reset pagination when entity count changes | Closes #2492

### LINKED ISSUE #2492: Reset Pagination After Entity List Filters Change
#### Steps to Reproduce

- refresh page and wait till everything loads but don't touch any filters or pagination yet

- if you do not have more than 6 dates in the list already, then change the pagination "per page" value to 2

 - click to view page 2 of the dates

 - now click to view filters, and from the "show" dropdown, select "all active and upcoming" (assuming that your dates list has at least one active or upcoming date in it)

 - the "no results found" notice should appear

 - if you now click on the "page 1" button in the pagination, a result should appear

Looks like we need to reset the pagination if the number of results changes as a result of other filters.

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR:
- Makes changes to `useEntityPagination` hook to make sure the pagination resets when entity count changes.
- Closes #2492

### CODE REVIEW

File: assets/src/application/ui/layout/entityList/pagination/useEntityPagination.ts [hunk 1]
```diff
@@ -10,6 +10,13 @@ const useEntityPagination = <E extends Entity>({ entities }: EntityListComponent
 	const [perPage, setPerPage] = useState(6);
 	const paginatedEntities = slice<E>(perPage * (pageNumber - 1), perPage * pageNumber, entities);
 	const total = entities.length;
+	const previousCount = useRef(total);
```
Comment (nicolad) [inline assets/src/application/ui/layout/entityList/pagination/useEntityPagination.ts]: clever :+1:
