### PR TITLE
Fix filter bar buttons tooltip | Closes #2652

### LINKED ISSUE #2652: Filter Bar Table View and Card View Button Tooltips Do Not Close
If you click on either of the Table View or Card View buttons in either of the filter bars, the tooltips that appear when you first click on them do not disappear after the view changes and you are left with something like this:

I'm guessing it is a memoization issue

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR fixes the issue of filter bar buttons tooltip not closing. The issue was because of the current view button getting disabled thus preventing `focus` and `blur` events.

### CODE REVIEW

File: assets/src/application/ui/layout/entityList/filterBar/buttons/ToggleLegendButton.tsx [hunk 1]
```diff
@@ -19,7 +20,7 @@ const ToggleLegendButton: React.FC<ToggleLegendButtonProps> = ({ listId, showLeg
 		</animated.div>
 	);
 	const filterId = `ee-toggle-legend-btn-${listId}`;
-	const tooltip = __(`${showLegend ? 'hide' : 'show'} legend`);
+	const tooltip = showLegend ? __('hide legend') : __('show legend');
```
Comment (manzoorwanijk) [inline assets/src/application/ui/layout/entityList/filterBar/buttons/ToggleLegendButton.tsx:23]: @nicolad please note that translation functions cannot handle variables. If you want use variables, then use `sprintf`.

File: assets/src/application/ui/layout/entityList/filterBar/buttons/CardViewFilterButton.tsx [hunk 2]
```diff
@@ -6,25 +6,25 @@ import { __ } from '@wordpress/i18n';
...
 	return (
 		<EspressoButton
 			buttonType={EspressoButtonType.MINIMAL}
 			className={className}
-			disabled={view === 'card'}
 			icon={<AppstoreFilled />}
 			id={filterId}
 			label={__('card view')}
-			onClick={setCardView}
+			onClick={view !== 'card' ? setCardView : null}
```
Comment (nicolad) [inline assets/src/application/ui/layout/entityList/filterBar/buttons/CardViewFilterButton.tsx:22]: :+1:

File: assets/src/application/ui/layout/entityList/filterBar/buttons/ToggleLegendButton.tsx (hunk 1 above)
Comment (nicolad) [reply assets/src/application/ui/layout/entityList/filterBar/buttons/ToggleLegendButton.tsx:23]: ok, thx for explanation
