### PR TITLE
Fix the issue caused by passing InfinitySymbol as initial value.

### LINKED ISSUE #1789: Some inline editable fields result in an error if no change is made to the value.
The fields like `capacity` for datetime and `quantity` for ticket when edited inline, result in an error if you decide not to make any change after switching to edit mode. It happens only if the field has a non-infinity value.

**To Reproduce**

1. Click on the capacity of a datetime.
2. Click anywhere else without making any change.
3. See the error in console.

**Expected behavior**
The focus should be taken away from the field and it should go back to display mode.

### PR DESCRIPTION
**Pull request by manzoorwanijk**
Fixes #1789 

## How has this been tested
monkey testing

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.
* [ ] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

File: assets/src/utils/parse-infinity.js [hunk 1]
```diff
@@ -20,13 +20,10 @@ const parseInfinity = ( number, asInt = false, forDb = false ) => {
...
 		value === Infinity ||
 		isNil( value );
-	number = representsInfinity( number ) || (
-		number.type &&
-		number.type.name === 'InfinitySymbol' &&
-		representsInfinity( number.props.value )
-	) ?
-		Infinity :
-		number;
+	if ( number && number.type && number.type.name === 'InfinitySymbol' ) {
```
Comment (nicolad) [inline assets/src/utils/parse-infinity.js]: It would be nice to have this plugin: https://babeljs.io/docs/en/next/babel-plugin-proposal-optional-chaining.html
Have used it on previous project, didn't had any issue.
With that plugin, we'd have:
`	if ( numbe?r.type?.name && number.type.name === 'InfinitySymbol' ) { ...`
***
note: this is optional, thus I do approve the PR with the current solution

Comment (manzoorwanijk) [reply assets/src/utils/parse-infinity.js]: Yes, optional chaining can be enabled. I have some other suggestions for that part of the code that I want to discuss with you and @tn3rb

**Comment by tn3rb** [comment]
changes look good

we should add a unit test for this utility and verify that it handles all possible conditions correctly

**Comment by manzoorwanijk** [comment]
> 
> 
> changes look good
> 
> we should add a unit test for this utility and verify that it handles all possible conditions correctly

Yes, It needs that.
