### PR TITLE
TAM and WP plugins page fixes | Closes #2794

### LINKED ISSUE #2794: TAM functions being used as hooks
`getBodyRows` and `getHeaderRows` inside `/domain/eventEditor/ui/ticketAssignmentsManager/components/table` are used as hooks, they should be renamed to start with `use`.

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR:
- Fixes hook names in TAM
- Creates root element needed for WP Plugins page.

### CODE REVIEW

File: assets/src/domain/wpPluginsPage/index.tsx [hunk 1]
```diff
@@ -14,9 +14,14 @@ const info = pathOr<ExitSurveyInfo>(null, ['eejsdata', 'data', 'exitModalInfo'],
...
+	const container = document.getElementById('wpfooter');
 
-	render(<ExitSurvey deactivationUrl={url} />, container);
+	const root = document.createElement('div');
+	root.id = 'ee-exit-survey-modal';
+
+	container.prepend(root);
+
+	render(<ExitSurvey deactivationUrl={url} />, root);
 };
```
Comment (tn3rb) [inline assets/src/domain/wpPluginsPage/index.tsx:25]: if you rebase onto latest EDTR/master you can use `/application/services/utilities/dom/renderDomElement.ts` for this

Comment (manzoorwanijk) [reply assets/src/domain/wpPluginsPage/index.tsx:25]: Oh, cool 👍

File: assets/src/domain/wpPluginsPage/index.tsx [hunk 2]
```diff
@@ -14,14 +14,13 @@ const info = pathOr<ExitSurveyInfo>(null, ['eejsdata', 'data', 'exitModalInfo'],
...
-	const root = document.createElement('div');
-	root.id = 'ee-exit-survey-modal';
-
-	container.prepend(root);
-
-	render(<ExitSurvey deactivationUrl={url} />, root);
+	renderDomElement({
+		appendToTarget: false,
+		domElementToRender: <ExitSurvey deactivationUrl={url} />,
+		containerID: 'ee-exit-survey-modalo',
```
Comment (tn3rb) [inline assets/src/domain/wpPluginsPage/index.tsx:21]: modalo ?
