### PR TITLE
EntityList fixes and Improvements | Closes #2550

### LINKED ISSUE #2550: EntityList types, API and consumer components are inconsistent
- `useTicketItem` and `useDatetimeItem` are being used inside a callback in `TableView.tsx`
- `EntityList` uses `CardList` and `TableView` differently, while as they should behave in same manner with respect to what is passed to them.
- Types defined in `/application/ui/layout/entityList/types.ts` are inconsistent
- Many types in `/domain/eventEditor/interfaces/types.ts` are useless

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR:
- Simplifies types and API for `EntityList`
- Updates date and ticket list components to use the new API
- Removes unnecessary types to use `EntityListItemProps`
- Replaces deprecated `React.ReactType` with `React.ComponentType`
- Closes #2550

### CODE REVIEW

File: assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/EditDateButton.tsx [hunk 1]
```diff
@@ -2,12 +2,11 @@ import React from 'react';
 import { __ } from '@wordpress/i18n';
 
 import { EspressoButton, Icon } from '@application/ui/input';
-import { EditItemButtonProps } from '@edtrInterfaces/types';
 import { useDatetimeContext } from '@edtrHooks/index';
 import { useDatetimeItem } from '@edtrServices/apollo/queries';
 import { useFormModal } from '@appLayout/formModal';
 
-const EditDateButton: React.FC<EditItemButtonProps> = ({ ...rest }) => {
```
Comment (manzoorwanijk) [inline assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/EditDateButton.tsx]: There were no props being passed, so I removed these at many places.

File: assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/TableView.tsx [hunk 2]
```diff
@@ -2,25 +2,24 @@ import React from 'react';
...
+// const noZebraStripe = ['row', 'stripe', 'name', 'actions'];
 
 /**
  * EditorDateEntitiesListView
  * Displays event date details in a standard list table like view
  */
-const TableView: React.FC<TableViewProps> = ({ className, displayStartOrEndDate, entities: datetimes, ...props }) => {
-	const formRows = datetimes.map(({ id }) => {
-		const datetime = useDatetimeItem({ id });
-		const columns = datesListTableRow({ datetime, displayStartOrEndDate, ...props });
```
Comment (manzoorwanijk) [inline assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/TableView.tsx]: I am surprised that a hook is used inside a callback. This mistake has been made many times now. We need to get ESLint working for react-hook-rules

File: assets/src/domain/eventEditor/ui/tickets/ticketsList/tableView/TableView.tsx [hunk 3]
```diff
@@ -18,10 +17,11 @@ import './styles.scss';
  * EditorTicketsListView
  * Displays tickets in a standard list table like view
  */
-const TableView: React.FC<TableViewProps> = ({ className, displayStartOrEndDate, entities: tickets, ...props }) => {
-	const formRows = tickets.map(({ id }) => {
-		const ticket = useTicketItem({ id });
-		const columns = ticketsListTableRow({ displayStartOrEndDate, ticket, ...props });
```
Comment (manzoorwanijk) [inline assets/src/domain/eventEditor/ui/tickets/ticketsList/tableView/TableView.tsx]: Same here regarding react hook inside callback.

File: assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/TableView.tsx (hunk 2 above)
Comment (tn3rb) [reply assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/TableView.tsx]: oh yuk... ya i totally missed that in my reviews
good catch

i think this was done because the entities were not refreshing after changes were made to them, so we'll have to watch out to make sure that they are not displaying stale copies
