### PR TITLE
Fixed duplicate subregions issue Fixes #832

### LINKED ISSUE #832: Multiple states can appear for the United States under certain conditions
**Seen on a recent version of Event Espresso**

**Summary**
I was testing this issue (https://github.com/eventespresso/event-espresso-core/issues/734) on Event Smart staging and noticed that the site had duplicate entries for the states for the United States afterward.

I ran additional testing on different websites and was able to reproduce the issue on a new site and an old site.

**Steps to reproduce**
Go through the steps here: https://github.com/eventespresso/event-espresso-core/issues/734

**Reported or seen on**
- https://lorenzoinvisible.makeeventsnotwar.com/wp-admin/admin.php?page=espresso_general_settings
- https://lorenzowp313.makeeventsnotwar.com/wp-admin/admin.php?page=espresso_general_settings

**Other notes**
Kristin was able to verify this issue and there are more affected sites here: https://github.com/eventespresso/eventsmart.com-website/issues/341#issuecomment-448367177

### PR DESCRIPTION
**Pull request by tn3rb**
## Problem this Pull Request solves
Fixes #832
Could not recreate the issue described in 832 locally no matter what I did.
However it was obvious from looking over the code that there could be better defences against preventing subregions from getting saved in the case where they already exist. This branch adds a check to verify that a subregion does not already exist before inserting a new record for it.

As well, this branch also calls the logic for retrieving and inserting subregions when a user visits the **Event Espresso - General Settings** > **Countries** admin page tab and selects a country from the dropdown that currently does not have any associated subregions.

## testing

- follow the steps outlined by @lorenzocaum on #832, specifically the steps he follows in the videos clips he posted
- [x] confirm that duplicate subregions do not get added for a country
- [ ] confirm that the above does not occur on EventSmart
- visit the **Event Espresso - General Settings** > **Countries** admin page tab and select a country from the dropdown that you have never used before and does not already have subregions for it within your database.
- [x] confirm that the **States/Provinces** section is populated with states (if not, then verify that the country you selected has a corresponding data file here: https://github.com/eventespresso/countries-and-subregions/tree/master/countries)
- feel free to experiment with subregions in this branch and attempt to find any other issues
- plz compare any potential issues against master branch to determine if they are caused by the work in this branch

### CODE REVIEW

File: core/services/address/CountrySubRegionDao.php [hunk 1]
```diff
@@ -228,4 +236,37 @@ private function saveSubRegionData(stdClass $country, $sub_regions = array())
...
+     * @throws ReflectionException
+     */
+    private function getExistingStateAbbreviations($CNT_ISO)
+    {
+        $existing_sub_region_IDs = [];
+        $existing_sub_regions = $this->state_model->get_all(array(
+            array(
+                'Country.CNT_ISO' => array(
+                    'IN',
+                    [$CNT_ISO]
```
Comment (nerrad) [inline core/services/address/CountrySubRegionDao.php]: Oh nice, I forgot that short form array syntax was introduced with PHP 5.4!

Comment (nerrad) [reply core/services/address/CountrySubRegionDao.php]: Even though I approved this, there's some failing code linting issues that need to be addressed.

**Comment by nerrad** [comment]
@tn3rb in the future, I don't think its necessary to push back code for a code review where only style fixes are made (especially when the original review approved).  You can force the merge in those cases (which you're going to have to do anyways here because the branch is out of date and my review will be dismissed).
