### PR TITLE
TAM - fix errors | Closes #2555

### LINKED ISSUE #2555: Ticket Assignments Manager Perma Errors
If a ticket or datetime is missing assignments then an error appears instructing you that entities require at least one relation (paraphrasing), but the error message will not go away and the submit button will not activate after correcting the issue.

Even changing every single cell in the table to have a relation will not resolve the problem:

note: it works correctly for the ALL Tickets Assignments Button at the bottom of the dates list, meaning if you resolve ALL missing relations for every date and ticket, then you can submit the changes.

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR:
- Updates `useAssignmentManager` and `useTAMStateManager` to expose `initialize()`
- Initializes data conditionally to use relations only for dates used in TAM
- Closes #2555

### CODE REVIEW

File: assets/src/domain/eventEditor/ui/ticketAssignmentsManager/TicketAssignmentsManager.tsx [hunk 1]
```diff
@@ -1,13 +1,28 @@
...
+
+	useEffect(() => {
+		if (!isInitialized()) {
+			// If TAM is only for a single datetime
+			// limit relations to that datetime
+			const forDate = assignmentType === 'forDate' ? entityId : null;
+			// initialize with existing data
+			initialize(relations.getData(), forDate);
+		}
+	}, [isInitialized()]);
```
Comment (nicolad) [inline assets/src/domain/eventEditor/ui/ticketAssignmentsManager/TicketAssignmentsManager.tsx]: can this be executed in `useTAMState` and have just the result here?
it is a bit strange to see a function being executed as a dependency

File: assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useAssignmentManager.ts [hunk 2]
```diff
@@ -76,19 +77,25 @@ const useAssignmentManager = (): AM => {
...
+			// limit relations to that datetime
+			const relationalEntityToUse =
+				entity === 'datetimes' && forDate ? pick([forDate], relationalEntity) : relationalEntity;
 			return map((relation) => {
 				return pick(relationsToPick, relation);
-			}, relationalEntity);
+			}, relationalEntityToUse);
 		}, newData);
 
+		console.log('newData', newData);
```
Comment (nicolad) [inline assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useAssignmentManager.ts]: oops

File: assets/src/domain/eventEditor/ui/ticketAssignmentsManager/TicketAssignmentsManager.tsx (hunk 1 above)
Comment (manzoorwanijk) [reply assets/src/domain/eventEditor/ui/ticketAssignmentsManager/TicketAssignmentsManager.tsx]: That's pretty normal. It's been defined as a function to avoid stale value getting found to a scope, this way i gets the current value to avoid the issue caused by asynchronous state updates.

File: assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useAssignmentManager.ts (hunk 2 above)
Comment (manzoorwanijk) [reply assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useAssignmentManager.ts]: Already removed :)

File: assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useAssignmentManager.ts [hunk 3]
```diff
@@ -76,17 +77,21 @@ const useAssignmentManager = (): AM => {
...
-	const initialize: AM['initialize'] = (data: TAMRelationalData) => {
+	const initialize: AM['initialize'] = (data: TAMRelationalData, forDate) => {
 		const relationsToPick: Array<keyof TAMRelationalData> = ['datetimes', 'tickets'];
 		// pick only datetimes and tickets from relational data
 		let newData = pick(relationsToPick, data);
 
 		// Remove other relations from newData
 		// like ticket to price relations
-		newData = map((relationalEntity) => {
+		newData = mapObjIndexed((relationalEntity, entity) => {
```
Comment (nicolad) [inline assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useAssignmentManager.ts]: nice, didn't used yet `mapObjIndexed` :+1:

Comment (manzoorwanijk) [reply assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useAssignmentManager.ts]: `mapObjIndexed` is useful when you need the key as well.

File: assets/src/domain/eventEditor/ui/ticketAssignmentsManager/TicketAssignmentsManager.tsx [hunk 4]
```diff
@@ -13,15 +13,17 @@ const TicketAssignmentsManager: React.FC<TAMProps> = ({ assignmentType, entityId
 	const relations = useRelations();
 	const { initialize, isInitialized } = useTAMState();
 
+	const initialized = isInitialized();
+
```
Comment (nicolad) [inline assets/src/domain/eventEditor/ui/ticketAssignmentsManager/TicketAssignmentsManager.tsx]: NOOOICE :taco:
