### PR TITLE
Fix TPC decimal palces | Closes #2806

### LINKED ISSUE #2806: TPC decimal places are messed up when switching reverse calculate
[See this](https://github.com/eventespresso/event-espresso-core/issues/2797#issuecomment-627221425)

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR fixes TPC decimal places based on site currency config.

### CODE REVIEW

File: assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/stateListeners/useInitStateListeners.ts [hunk 1]
```diff
@@ -5,18 +5,20 @@ import { calculateBasePrice, calculateTicketTotal } from '../utils';
...
 	const updateBasePrice = useCallback(() => {
-		const newPrices = calculateBasePrice(getData());
+		const newPrices = calculateBasePrice(getData(), formatAmount);
 		setPrices(newPrices);
 	}, [getData, setPrices]);
 
 	const updateTicketTotal = useCallback(() => {
 		const ticketTotal = calculateTicketTotal(getData());
-		updateTicketPrice(ticketTotal);
+		updateTicketPrice(parseFloat(formatAmount(ticketTotal)));
```
Comment (nicolad) [inline assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/stateListeners/useInitStateListeners.ts:21]: ramda's `pipe` would come handy, if these are curried
