### PR TITLE
DatePicker and TimePicker fixes | Closes #2616

### LINKED ISSUE #2616: EDTR Crashes (HARD) if you Backspace Delete in Timepicker Field in Date Edit Form
### steps to reproduce the issue

- open edit date form for any date

- click on timepicker for either start or end date

- start hitting backspace to delete the existing text

- :boom: **entire** EDTR crashes

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR fixes the issue of EDTR crashing when pressing backspace on picker input. It also fixes the issue of month name and weekday names not visible on DatePicker
Closes #2616

### CODE REVIEW

File: assets/src/application/ui/input/DateTimePicker/CustomDate.ts [hunk 1]
```diff
@@ -49,13 +49,30 @@ const CustomDate: GenerateConfig<Date> = {
...
+			'Apr',
+			'May',
+			'Jun',
+			'Jul',
+			'Aug',
+			'Sep',
+			'Oct',
+			'Nov',
+			'Dec',
+		],
```
Comment (tn3rb) [inline assets/src/application/ui/input/DateTimePicker/CustomDate.ts]: needs i18n ie: `__()`

(EDIT)  oops... just noticed the todo comment :facepalm:
